name: hoodsec.org
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis"]
title: hoodsec.org News
production_url: http://www.hoodsec.org

title: hoodsec
email: diff@cloudflare.com
description: >
  CitySec meetup for Information Security professionals/hoodlums in
  Oakland/East Bay. Meets last Thursday of every month at Radio Bar
  unless otherwise specified.
baseurl: ""
url: "http://www.hoodsec.org"
twitter_username: hoodsec
github_username:  hoodsec